### ISSUE TITLE
Unable to install :(

### ISSUE THREAD

**Issue by elkuku** [eddieajau/joomla-rest-server#2]
Currently the command `composer install` results in the following output:

```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install joomla/framework 1.0-beta2
    - joomla/application 1.0-beta2 requires joomla/filesystem 1.0-beta2 -> satisfiable by joomla/framework[1.0-beta2], joomla/filesystem[1.0-beta2].
    - joomla/filesystem 1.0-beta2 requires joomla/client 1.0-beta2 -> satisfiable by joomla/framework[1.0-beta2].
    - Installation request for joomla/application 1.0-beta2 -> satisfiable by joomla/application[1.0-beta2], joomla/framework[1.0-beta2].
```

Now, comparing
https://github.com/joomla/joomla-framework-filesystem/blob/master/composer.json
to
https://github.com/joomla/joomla-framework/blob/staging/src/Joomla/Filesystem/composer.json
it seems that only `joomla/joomla-framework-filesystem/composer.json` contains the requirement.
Could it be enough to just run the subtree-split-thingy script ?

**Comment by eddieajau** [comment]
I'm not sure what's going on there. I think because each package and the whole framework is registered Composer gets confused. I'll talk to Don about what could be going wrong.

**Comment by dongilbert** [comment]
We've removed the `joomla/client` package, since it was a mashup of LDAP and FTP access code. Probably should have left it around for situations like this. Sorry about that.

This will be fixed in the next beta, since `joomla/filesystem` no longer requires the client package. To get around it now, you can change the versions in the `composer.json` to `dev-master` instead of `1.0-beta2`.
